FROM node:boron-alpine

EXPOSE 3000

RUN apk add --update tini \
  && mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json package.json

RUN npm install \
  && npm cache clean --force

COPY . . 

CMD ["tini", "--", "node", "./bin/www"]